descriptionFormat: '{product.title} - {title}'
handle: equipment
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: true
hasVariants: true
name: Equipment
productFieldLayouts:
  fa8d8c36-eb8a-4883-b413-eaec9c86bd87:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            warning: null
            width: 100
          -
            fieldUid: 5f3f9d21-e4a4-40d6-b80f-a92d99e02926
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            warning: null
        name: Variants
        sortOrder: 2
productTitleFormat: ''
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81:
    hasUrls: true
    template: _views/products/equipment
    uriFormat: 'equipment/{slug}'
skuFormat: ''
titleFormat: '{product.title}'
variantFieldLayouts:
  53a32148-ef70-45d9-aa6b-80f1dde558ac:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
