contentColumnType: string(500)
fieldGroup: 6aa1ad27-db4b-4af9-8658-d93eff3d4512
handle: map
instructions: ''
name: Map
searchable: false
settings:
  maxLength: '500'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
