columnSuffix: null
contentColumnType: text
fieldGroup: 6aa1ad27-db4b-4af9-8658-d93eff3d4512 # Common
handle: address
instructions: ''
name: Address
searchable: false
settings:
  addRowLabel: 'Add a line'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Line
            -
              - handle
              - line
            -
              - width
              - ''
            -
              - type
              - singleline
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
