defaultPlacement: end
enableVersioning: true
handle: account
name: Account
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: _views/account/index
    uriFormat: 'account/{slug}'
structure:
  maxLevels: 1
  uid: 3ed5e76d-6bdf-4c94-95ab-b7f24b1f1333
type: structure
