enableVersioning: true
handle: equipmentLanding
name: Equipment
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: equipment
type: single
